environment:
  matrix:  
  - job_name: Arcemu VS2010 build
    appveyor_build_worker_image: Visual Studio 2013
    CMAKE_GENERATOR_NAME: Visual Studio 10 2010
    
  - job_name: Arcemu VS2017 build
    appveyor_build_worker_image: Visual Studio 2017
    CMAKE_GENERATOR_NAME: Visual Studio 15 2017
    
matrix:
  fast_finish: true

build_script:
- cmd: >-
     mkdir build
     
     cd build
     
     cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=Debug ..\cmake
     
     msbuild Arcemu.sln
     
     ctest -C Debug --verbose
